<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="1" ignored="0" total="5" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-08-09T19:21:55 IST" name="Suite" finished-at="2024-08-09T19:24:08 IST" duration-ms="133750">
    <groups>
      <group name="ErrorHandling">
        <method signature="ErrorValidationTest.loginErrorValidation()[pri:0, instance:Srilatha.SeleniumFrameworkDesign.Tests.ErrorValidationTest@26abb146]" name="loginErrorValidation" class="Srilatha.SeleniumFrameworkDesign.Tests.ErrorValidationTest"/>
      </group> <!-- ErrorHandling -->
      <group name="purchase">
        <method signature="SubmitOrderTest.submitOrder(java.util.HashMap)[pri:0, instance:Srilatha.SeleniumFrameworkDesign.Tests.SubmitOrderTest@7ce69770]" name="submitOrder" class="Srilatha.SeleniumFrameworkDesign.Tests.SubmitOrderTest"/>
      </group> <!-- purchase -->
    </groups>
    <test started-at="2024-08-09T19:21:55 IST" name="SubmitOrderTest" finished-at="2024-08-09T19:22:59 IST" duration-ms="64170">
      <class name="Srilatha.SeleniumFrameworkDesign.Tests.SubmitOrderTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:Srilatha.SeleniumFrameworkDesign.Tests.SubmitOrderTest@7ce69770]" started-at="2024-08-09T19:21:55 IST" name="launchApplication" finished-at="2024-08-09T19:22:01 IST" duration-ms="6349" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="submitOrder(java.util.HashMap)[pri:0, instance:Srilatha.SeleniumFrameworkDesign.Tests.SubmitOrderTest@7ce69770]" started-at="2024-08-09T19:22:01 IST" name="submitOrder" data-provider="getData" finished-at="2024-08-09T19:22:22 IST" duration-ms="20740" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{pwd=Fjot&023, productname=ZARA COAT 3, email=srilatha.i@gmail.com}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:Srilatha.SeleniumFrameworkDesign.Tests.SubmitOrderTest@7ce69770]" started-at="2024-08-09T19:22:22 IST" name="launchApplication" finished-at="2024-08-09T19:22:33 IST" duration-ms="10677" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="submitOrder(java.util.HashMap)[pri:0, instance:Srilatha.SeleniumFrameworkDesign.Tests.SubmitOrderTest@7ce69770]" started-at="2024-08-09T19:22:33 IST" name="submitOrder" data-provider="getData" finished-at="2024-08-09T19:22:59 IST" duration-ms="26137" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{pwd=Fjot&023, productname=ADIDAS ORIGINAL, email=sriraghava.m@gmail.com}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
      </class> <!-- Srilatha.SeleniumFrameworkDesign.Tests.SubmitOrderTest -->
    </test> <!-- SubmitOrderTest -->
    <test started-at="2024-08-09T19:23:01 IST" name="ErrorValidationTest" finished-at="2024-08-09T19:24:08 IST" duration-ms="67548">
      <class name="Srilatha.SeleniumFrameworkDesign.Tests.ErrorValidationTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:Srilatha.SeleniumFrameworkDesign.Tests.ErrorValidationTest@26abb146]" started-at="2024-08-09T19:23:01 IST" name="launchApplication" finished-at="2024-08-09T19:23:26 IST" duration-ms="24690" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method retried="true" signature="loginErrorValidation()[pri:0, instance:Srilatha.SeleniumFrameworkDesign.Tests.ErrorValidationTest@26abb146]" started-at="2024-08-09T19:23:26 IST" name="loginErrorValidation" finished-at="2024-08-09T19:23:26 IST" duration-ms="745" status="SKIP">
          <exception class="org.junit.ComparisonFailure">
            <message>
              <![CDATA[expected:<Incorrect email [] password.> but was:<Incorrect email [or] password.>]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.junit.ComparisonFailure: expected:<Incorrect email [] password.> but was:<Incorrect email [or] password.>
at org.junit.Assert.assertEquals(Assert.java:115)
at org.junit.Assert.assertEquals(Assert.java:144)
at Srilatha.SeleniumFrameworkDesign.Tests.ErrorValidationTest.loginErrorValidation(ErrorValidationTest.java:31)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- org.junit.ComparisonFailure -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginErrorValidation -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:Srilatha.SeleniumFrameworkDesign.Tests.ErrorValidationTest@26abb146]" started-at="2024-08-09T19:23:26 IST" name="launchApplication" finished-at="2024-08-09T19:23:41 IST" duration-ms="14585" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="loginErrorValidation()[pri:0, instance:Srilatha.SeleniumFrameworkDesign.Tests.ErrorValidationTest@26abb146]" started-at="2024-08-09T19:23:41 IST" name="loginErrorValidation" finished-at="2024-08-09T19:23:42 IST" duration-ms="666" status="FAIL">
          <exception class="org.junit.ComparisonFailure">
            <message>
              <![CDATA[expected:<Incorrect email [] password.> but was:<Incorrect email [or] password.>]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.junit.ComparisonFailure: expected:<Incorrect email [] password.> but was:<Incorrect email [or] password.>
at org.junit.Assert.assertEquals(Assert.java:115)
at org.junit.Assert.assertEquals(Assert.java:144)
at Srilatha.SeleniumFrameworkDesign.Tests.ErrorValidationTest.loginErrorValidation(ErrorValidationTest.java:31)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- org.junit.ComparisonFailure -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginErrorValidation -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:Srilatha.SeleniumFrameworkDesign.Tests.ErrorValidationTest@26abb146]" started-at="2024-08-09T19:23:43 IST" name="launchApplication" finished-at="2024-08-09T19:23:54 IST" duration-ms="11172" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="productErrorValidation()[pri:0, instance:Srilatha.SeleniumFrameworkDesign.Tests.ErrorValidationTest@26abb146]" started-at="2024-08-09T19:23:54 IST" name="productErrorValidation" finished-at="2024-08-09T19:24:08 IST" duration-ms="14480" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- productErrorValidation -->
      </class> <!-- Srilatha.SeleniumFrameworkDesign.Tests.ErrorValidationTest -->
    </test> <!-- ErrorValidationTest -->
  </suite> <!-- Suite -->
</testng-results>
